fix: test run on Node v22
Import from ts instead of js to avoid

SyntaxError: Named export 'SourcePrioritiesData' not found. The requested module '../dist/deltaPriority.js' is a CommonJS module, which may not support all module.exports as named exports.
C