chore: pin geolib to 2.0.24
2.0.26 fails with

TypeError: geolib.isPointInCircle is not a function
    at checkPosition (/Users/tjk/git-workspace/signalk/server-node/lib/subscriptionmanager.js:223:19)

Version 3 is out, so if this needs further work I suggest we
consider upgrading to that. But maybe after it settles a little
while.